name: local_storage_skills_api
description: Skills package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  skills_api:
    path: ../skills_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
